### ISSUE TITLE
Add Symbols-Module

### ISSUE THREAD

**Issue by der-lukas** [marckrenn/framer-testDrive#1]
Please add my Symbols-Module, it would be perfect if I wouldn't have to update every Demo Prototype when I push a new version!

```
!symbols: {
  author: "Lukas Guschlbauer",
  description: "A module to create symbols in Framer.",
  repo: "https://github.com/der-lukas/framer-Symbols",
  source: "https://raw.githubusercontent.com/der-lukas/framer-Symbols/master/Symbol.coffee"
}
```

**Comment by marckrenn** [comment]
Done!

Just add the testDrive-snippet and `testDrive.module "symbols"` to the top of your demos :)
